name: rebuild

on:
  schedule:
    - cron:  '0 6 * * 1,3,5' # Runs every Mon, Wed and Fri at 6am

jobs:
  github-pages:
    runs-on: ubuntu-latest
    name: Update GitHub Pages initiatives
    steps:
      - name: Jekyll update github pages without new commit
        uses: DP6/jekyll-update-pages-action@v1.0.1
        with:
          DEPLOY_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          USER: ${{ secrets.GH_PAGES_USER }}
          FILTER: "is%3Apublic%20org%3Adp6"
